# Generated by Django 3.1 on 2020-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200822_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_spacial',
            new_name='is_special',
        ),
    ]
